spring.application.name=NovaTrace

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/findme_db
spring.datasource.username=postgres
spring.datasource.password=Dharshu@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Gemini API Configuration for Spring AI
spring.ai.openai.api-key=AIzaSyDhFkdcwMzef90Kn61iA2ayl-U45sXjes4
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-1.5-flash